# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: silencht's blog
subtitle: ''
description: ''
keywords:
author: silencht
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://silencht.github.io
root: /
permalink: wiki/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang #自动侦测页面语言
skip_render:
  - README.md
  - '_posts/**/embed_page/**'
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
#当资源文件管理功能打开后，Hexo将会在你每一次通过 hexo new [layout] <title> 命令
#创建新文章时自动创建一个文件夹。这个资源文件夹将会有与这个文章文件一样的名字。
#将所有与你的文章有关的资源放在这个关联文件夹中之后，你可以通过相对路径来引用它们，
#这样你就得到了一个更简单而且方便得多的工作流。
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: root
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page


archive_generator:
  enabled: true
  per_page: 5
  yearly: true
  monthly: true
  daily: false
  order_by: -date

tag_generator:
  per_page: 10

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
jsonContent:
  meta: false
  pages:
    title: true
    date: true
    path: true
    text: true
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true

### Creat sitemap
sitemap:
  path: sitemap.xml #

#自动向你的链接添加 nofollow 属性，以确保搜索引擎不会对这些链接产生过多的关注
nofollow:
  enable: true 
  exclude:
  
theme: Wikitten

math:
  enable: true
  engine: mathjax
  per_page: false

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/silencht/silencht.github.io
  branch: gh-pages




